# Generated by Django 5.2.8 on 2025-11-14 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0004_alter_scan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.CharField(max_length=500)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scan')),
            ],
            options={
                'verbose_name': 'Finding',
                'verbose_name_plural': 'Findings',
                'ordering': ['-created_at'],
            },
        ),
    ]
