# Generated by Django 5.2.8 on 2025-11-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreFindingDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ignored Email Domain',
                'verbose_name_plural': 'Ignored Email Domains',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='IgnoreFindingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ignored Finding Type',
                'verbose_name_plural': 'Ignored Finding Types',
                'ordering': ['type'],
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='commit_hash',
            field=models.CharField(default='aaaaaaaaaa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finding',
            name='commit_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='email',
            field=models.CharField(default='bbbbbbbbb', max_length=255),
            preserve_default=False,
        ),
    ]
