# Generated by Django 5.2.8 on 2025-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0002_ignorefindingdomain_ignorefindingtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='commit_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='finding',
            name='file',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='finding',
            name='repository',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='finding',
            name='type',
            field=models.CharField(max_length=512),
        ),
    ]
