# Generated by Django 5.2.8 on 2025-12-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0003_alter_finding_commit_url_alter_finding_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
