# Generated by Django 5.2.8 on 2025-11-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_alter_scan_options_scan_completed_at_scan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
