# Generated by Django 5.2.8 on 2025-11-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_alter_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
