# Generated by Django 5.2.8 on 2025-11-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_alter_scan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='ignored_findings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='ignored_repositories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='scanned_repositories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='scanned_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='total_findings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='total_repositories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='total_users',
            field=models.IntegerField(default=0),
        ),
    ]
