# Generated by Django 5.2.8 on 2025-11-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_scan_ignored_findings_scan_ignored_repositories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='scanned_users',
        ),
    ]
