# Generated by Django 5.2.8 on 2025-11-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_remove_scan_scanned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='total_users',
        ),
    ]
