# Generated by Django 5.2.8 on 2025-11-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0007_remove_scan_total_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='type',
            field=models.CharField(choices=[('org_repos', 'Organization Repositories'), ('org_users', 'Organization Users'), ('search_repos', 'Search Repositories')], default='org_repos', max_length=255),
        ),
    ]
