# Generated by Django 5.2.8 on 2025-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_alter_scan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='type',
            field=models.CharField(choices=[('org_repos', 'Organization Repositories'), ('org_users', 'Organization Users'), ('search_code', 'Search Code'), ('search_commits', 'Search Commits'), ('search_issues', 'Search Issues'), ('search_repos', 'Search Repositories')], default='org_repos', max_length=255),
        ),
    ]
