# Generated by Django 5.2.8 on 2025-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reposcanhistory',
            name='findings_count',
            field=models.IntegerField(default=0),
        ),
    ]
