# Generated by Django 5.2.8 on 2025-11-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reposcanhistory_findings_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reposcanhistory',
            name='scan',
        ),
    ]
