# Generated by Django 5.2.8 on 2025-12-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_reposcanhistory_scan"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skip_recent_days",
                    models.IntegerField(
                        default=15,
                        help_text="Skip repository scanned within this many days",
                    ),
                ),
                (
                    "include_unverified",
                    models.BooleanField(
                        default=False,
                        help_text="Include unverified secrets from TruffleHog",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": ("System Settings",),
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
