# Generated by Django 5.2.8 on 2025-12-30 09:40

from django.db import migrations, models


def invert_unverified_to_verified_only(apps, schema_editor):
    """
    Convert include_unverified to verified_only with inverted logic
    include_unverified=False -> verified_only=True
    include_unverified=True -> verified_only=False
    """
    SystemSettings = apps.get_model("core", "SystemSettings")
    for setting in SystemSettings.objects.all():
        setting.verified_only = not setting.include_unverified
        setting.save()


def invert_verified_only_to_unverified(apps, schema_editor):
    """Reverse migration: convert back to include_unverified"""
    SystemSettings = apps.get_model("core", "SystemSettings")
    for setting in SystemSettings.objects.all():
        setting.include_unverified = not setting.verified_only
        setting.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="verified_only",
            field=models.BooleanField(
                default=True,
                help_text="Only scan for verified secrets (faster, fewer false positives)",
            ),
        ),
        migrations.RunPython(
            invert_unverified_to_verified_only,
            reverse_code=invert_verified_only_to_unverified,
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="include_unverified",
        ),
    ]
