# Generated by Django 5.2.8 on 2026-01-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_include_unverified_to_verified_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="org_repos_only",
            field=models.BooleanField(
                default=False,
                help_text="Only scan repositories owned by organizations (not individual users)",
            ),
        ),
    ]
