# Generated by Django 5.2.8 on 2025-11-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('failed', 'Failed')], default='disconnected', max_length=255),
        ),
    ]
