# Generated by Django 5.2.8 on 2025-11-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_userintegration_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userintegration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Integration', 'verbose_name_plural': 'Integrtions'},
        ),
    ]
