# Generated by Django 5.2.8 on 2025-11-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_userintegration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegration',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('pending', 'Pending'), ('failed', 'Failed')], default='disconnected', max_length=255),
        ),
    ]
