# Generated by Django 5.2.8 on 2026-01-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_alter_userintegration_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userintegration",
            name="error_message",
            field=models.TextField(
                blank=True, default="", help_text="Error message if validation failed"
            ),
        ),
        migrations.AddField(
            model_name="userintegration",
            name="last_validated_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time the token was validated", null=True
            ),
        ),
    ]
