[project]
name = "api"
version = "1.0.0"
description = "Django REST API for automated security scanning of GitHub repositories to detect exposed secrets and sensitive information"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "celery==5.6.3",
    "cryptography==50.0.1",
    "django==6.1",
    "django-cors-headers==4.9.0",
    "django-filter==26.1",
    "djangorestframework==3.18.0",
    "djangorestframework-simplejwt==5.5.1",
    "drf-spectacular==0.30.0",
    "gunicorn==26.2.0",
    "psycopg2-binary==2.9.12",
    "pytest==9.1.1",
    "pytest-django==4.14.0",
    "python-dotenv==1.2.3",
    "redis==8.1.0",
    "requests==2.34.2",
    "watchdog==6.0.0",
]
